"""empty message

Revision ID: 891db5f233b4
Revises: 
Create Date: 2023-07-06 17:35:07.422297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '891db5f233b4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sold_product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sale_price', sa.Double(), nullable=True),
    sa.Column('sale_date', sa.DateTime(), nullable=True),
    sa.Column('sale_qty', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sold_product')
    # ### end Alembic commands ###
