"""Added description field to Bundle

Revision ID: a315d28ceb43
Revises: 
Create Date: 2023-07-05 02:02:32.928722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a315d28ceb43'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bundles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bundles', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
